savannahghi/profileutils

README.md
Signed-off-by: Otieno Calvine <nyarangaotieno@gmail.com>
=> chore: add ci build status in the readme

go.mod, go.sum
=> chore: mod tidy

go.mod, go.sum, profile.go
=> chore: import scalar methods

go.mod, go.sum
=> chore: upgrade packages

go.mod, go.sum, profile.go
=> chore: move feedlib functions

profile.go, profile_test.go
=> chore: update profile functions

profile.go
=> feat: add user favorite navigation actions to profile

constants.go, models.go, nav_actions.go, permissions.go, profile.go, profile_test.go
=> feat: added a relationship between permissions and roles

profile.go, profile_test.go
=> feat: added roles attribute to userprofile

permissions.go, permissions_test.go
=> feat: added permissions and roles

permissions.go, permissions_test.go
=> feat: change allowedpermissions to scopes

permissions_test.go
=> test: add test for valid permission group

permissions.go
=> feat: add updated and updated by

profile.go
=> chore: permissions in user response

profile.go
=> chore:adding-user-assistant-to-user-profile

profile.go
=> adding docs

profile.go
=> add user profiles link

permissions.go
=> chore: add permissions for covers

profile.go
=> chore: Rename UserLink to ReferralLink

.github/workflows/ci.yml, mock/profile_mock.go
=> chore: add profile mock

permissions.go
=> change group type in the permission struct

profile.go
Signed-off-by: Dumbledore <mathenge@healthcloud.co.ke>
=> chore: add timestamp fields to Features

.github/workflows/ci.yml, go.mod, profile.go
add `hasHistoricalClaims` attribute to cover struct
Signed-off-by: DavidDexter <dmwangi@kineticengines.co.ke>
=> chore : extend cover struct
